### ISSUE TITLE
traduciendo el capítulo 5

### ISSUE THREAD

**Issue by come-maiz** [JaquerEspeis/inventar-con-python#10]
Voy a tomar el capítulo 5 para traducirlo

**Comment by eliastorres** [comment]
Pido este capítulo :)

**Comment by come-maiz** [comment]
Dele! Yo voy a tomar otro.

**Comment by jamescr** [comment]
He estado haciendo algunos PR con revisiones a las traducciones de los capítulos anteriores. Para mantener el orden me gustaría echar una mano traduciendo este capítulo. Viendo el repo de @eliastorres [había comenzado](https://github.com/eliastorres/inventar-con-python/commit/7459cae8d615347ba922dc73b12636c63b9ce968) con la traducción. ¿le parece si continuo la traducción que había iniciado y en cuanto termine le hago un PR a su repo?

**Comment by jamescr** [comment]
No pude terminar pero por acá va: https://github.com/jamescr/inventar-con-python/tree/issue10_capitulo5
