### ISSUE TITLE
Traduciendo capitulo 6

### ISSUE THREAD

**Issue by dtec83** [JaquerEspeis/inventar-con-python#12]

**Comment by come-maiz** [comment]
Yo voy a tomar este. Gracias @dtec83.

**Comment by jamescr** [comment]
He venido revisando los capítulos anteriores y traduciendo el 5. Me gustaría seguir aportando en el orden en que van los capítulo. No se si tienen algún avance de esta traducción a la que colaborar o si les parece la comienzo yo.
