### ISSUE TITLE
Traducción del capítulo 8

### ISSUE THREAD

**Issue by rlmrjmnz** [JaquerEspeis/inventar-con-python#15]
Voy a tomar el capítulo 8 para traducirlo

**Comment by jamescr** [comment]
Hola. En estas semanas hemos retomado la traducción del libro. Ya tenemos los capítulos del 1 al 7 entonces para mantener el orden de la traducción quería preguntarle si tiene algún avance en la traducción que nos pudiera compartir para echarle una mano o si le damos camino.

**Comment by jamescr** [comment]
Voy a echarle una mano con esta traducción.  Por acá la comencé https://github.com/jamescr/inventar-con-python/tree/cap8_issue15
