### ISSUE TITLE
Traduciendo el Cap 10

### ISSUE THREAD

**Issue by djcerdas** [JaquerEspeis/inventar-con-python#17]

**Comment by jamescr** [comment]
Ya estamos llegando al capítulo 10 en la traducción, quería preguntarle si tiene algún avance en la traducción que nos pudiera compartir para echarle una mano o si le damos camino.

**Comment by jamescr** [comment]
voy a comenzar esta traducción.

**Comment by djcerdas** [comment]
Hola,

He estado apretado en el trabajo estas semana, ya habia avanzado algo, pero
no he tenido chance de responder este correo.


Kind Regards,
------------------------------------
David J. Cerdas Pérez
Mobile: (+506) 8818-3771
Linkedin:   David J. Cerdas
<https://www.linkedin.com/in/david-jesús-cerdas-a56a6925>
Twitter:  @DJCerdas <https://twitter.com/DJCerdas>

**Comment by jamescr** [comment]
Entiendo. Entonces voy a comenzar con otro capítulo pero por favor cuando pueda suba lo que lleva delantado y así le echamos una mano.  😉

**Comment by jamescr** [comment]
Por acá (https://github.com/JaquerEspeis/inventar-con-python/pull/40) comencé la traducción de este capítulo.
